name: 'Validate API'
description: 'Validate API specification and compliance with rulesets'
inputs:
  manager-host:  
    description: 'API Manager hostname'
    required: true
  api-host:  
    description: 'Platform API hostname'
    required: true
  iam-apikey:  
    description: 'IAM API key - require this, apikey or username,password and realm'
    required: false
  apikey:  
    description: 'APIC API key - require this, iam-apikey or username,password and realm'
    required: false
  username:  
    description: 'API Manager username'
    required: false
  password:  
    description: 'API Manager password'
    required: false
  realm:  
    description: 'Realm for log in '
    default: "provider/default-idp-2"
    required: false
  provider-org:  
    description: 'Name of ID of provider org to publish to'
    required: true
  api-spec:  
    description: 'File name of api specification to validate'
    required: false
    default: 'api.yaml'    
branding:
  icon: 'upload-cloud'
  color: 'blue'
runs:
  using: "composite"
  steps:

  - name: Get APIC Toolkit
    shell: bash
    run: |
      curl -LO https://${{ inputs.manager-host }}/client-downloads/toolkit-linux.tgz
      tar -zxf toolkit-linux.tgz

  - name: Accept APIC license and check version
    shell: bash
    run: |
      ./apic  --insecure-skip-tls-verify --accept-license --live-help version

  - name: Login to API Manager with provided credentials
    shell: bash
    run: |
      if [[ "${{ inputs.iam-apikey }}" != "" ]]; then
        echo "Using IAM API Key"
        mkdir ~/.apiconnect/
        touch ~/.apiconnect/token
        ACCESS_TOKEN=$(curl -s "https://iam.cloud.ibm.com/identity/token" -H 'Content-Type: application/x-www-form-urlencoded' -H 'Accept: application/json' --data "grant_type=urn:ibm:params:oauth:grant-type:apikey&apikey=${{ inputs.iam-apikey}}" | jq .access_token -r)
        echo "${{ inputs.api-host}}/api: |
              refresh_token: \"\"
              access_token: ${ACCESS_TOKEN}" > ~/.apiconnect/token 
      fi
      if [[ "${{ inputs.apikey }}" != "" ]]; then
        echo "Using apikey"
        ./apic login  --insecure-skip-tls-verify --server ${{ inputs.api-host }} --sso --apiKey ${{ inputs.apikey }} --context provider
      fi
      if [[ "${{ inputs.username }}" != "" ]]; then
        echo "Using username/password"
        ./apic login --insecure-skip-tls-verify --server ${{ inputs.api-host }} --username ${{ inputs.username }} --password ${{ inputs.password }} --realm ${{ inputs.realm }}
      fi

  - name: Validate compliance with rulesets
    shell: bash
    run: |
      ./apic --mode governance compliance:validate  --insecure-skip-tls-verify --server ${{ inputs.api-host }} --org ${{ inputs.provider-org }} ${{ inputs.api-spec }} --format json | tee compliance.json      
      jq -cr '.errors[] | "::warning file=${{ inputs.api-file }},::title=\(.severity): \(.ruleset_name) \(.rule_name)::\(.message)"' compliance.json

      